from __future__ import annotations

from collections import OrderedDict

from models.macro_analysis import HypothesisTemplate, IssueCategoryConfig


ISSUE_CATEGORY_ORDER = (
    "inflation_policy",
    "growth_outlook",
    "labor_policy",
    "treasury_curve",
    "soft_landing_growth_scare",
    "cross_asset_risk",
    "custom",
)


def _hypothesis(
    hypothesis_id: str,
    title: str,
    description: str,
    expected_rules: tuple[str, ...],
    support_signal_groups: tuple[str, ...] = (),
    challenge_signal_groups: tuple[str, ...] = (),
    support_panel_ids: tuple[str, ...] = (),
    challenge_panel_ids: tuple[str, ...] = (),
) -> HypothesisTemplate:
    return HypothesisTemplate(
        hypothesis_id=hypothesis_id,
        title=title,
        description=description,
        expected_rules=expected_rules,
        support_signal_groups=support_signal_groups,
        challenge_signal_groups=challenge_signal_groups,
        support_panel_ids=support_panel_ids,
        challenge_panel_ids=challenge_panel_ids,
    )


ISSUE_CATEGORY_REGISTRY: dict[str, IssueCategoryConfig] = OrderedDict(
    [
        (
            "inflation_policy",
            IssueCategoryConfig(
                category_id="inflation_policy",
                display_name="Inflation and Fed Policy",
                description="Use this when the key question is whether inflation is cooling enough for the Federal Reserve to step away from restrictive policy.",
                primary_panels=("inflation", "labor"),
                secondary_panels=("yield_curve", "growth", "nelson_siegel"),
                primary_signal_groups=(
                    "realized_inflation",
                    "medium_term_inflation_pricing",
                    "long_run_inflation_anchor",
                    "labor_wage_pressure",
                    "household_inflation_expectations",
                ),
                secondary_signal_groups=("labor_slack", "growth_momentum", "front_end_rates", "curve_slope"),
                default_questions=(
                    "Is disinflation continuing or stalling?",
                    "Are longer-run inflation expectations still anchored?",
                    "Does the inflation mix support a less restrictive Fed stance?",
                    "Is wage pressure easing sufficiently to reduce policy concern?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "realized_inflation",
                    "market_inflation_pricing",
                    "wage_and_labor_pressure",
                    "policy_implications",
                    "counter_evidence",
                    "rates_implications",
                    "risks_and_watch_list",
                ),
                default_watch_questions=(
                    "Does CPI and PCE continue to cool on a 3M trend?",
                    "Do breakevens remain anchored?",
                    "Are wages and labor pressure easing together?",
                ),
                required_evidence_groups=(
                    "realized_inflation",
                    "medium_term_inflation_pricing",
                    "long_run_inflation_anchor",
                ),
                optional_evidence_groups=(
                    "labor_wage_pressure",
                    "household_inflation_expectations",
                    "front_end_rates",
                    "curve_slope",
                    "growth_momentum",
                    "labor_slack",
                ),
                hypotheses=(
                    _hypothesis(
                        "disinflation_intact",
                        "Disinflation remains intact",
                        "Realized inflation and market pricing still point toward slower inflation over time.",
                        ("realized_inflation", "medium_term_inflation_pricing", "long_run_inflation_anchor"),
                        support_signal_groups=(
                            "realized_inflation",
                            "medium_term_inflation_pricing",
                            "long_run_inflation_anchor",
                        ),
                        challenge_signal_groups=("labor_wage_pressure", "household_inflation_expectations"),
                    ),
                    _hypothesis(
                        "inflation_persistence",
                        "Inflation persistence remains a policy constraint",
                        "Wage pressure or sticky expectations could keep policy restrictive for longer.",
                        ("labor_wage_pressure", "household_inflation_expectations", "realized_inflation"),
                        support_signal_groups=("labor_wage_pressure", "household_inflation_expectations", "realized_inflation"),
                        challenge_signal_groups=("medium_term_inflation_pricing", "long_run_inflation_anchor"),
                    ),
                    _hypothesis(
                        "mixed_inflation_signals",
                        "Inflation signals are mixed",
                        "Realized inflation, market pricing and survey expectations are not aligned enough for a clean call.",
                        ("realized_inflation", "medium_term_inflation_pricing", "household_inflation_expectations"),
                        support_signal_groups=(
                            "realized_inflation",
                            "medium_term_inflation_pricing",
                            "long_run_inflation_anchor",
                            "household_inflation_expectations",
                        ),
                    ),
                ),
            ),
        ),
        (
            "growth_outlook",
            IssueCategoryConfig(
                category_id="growth_outlook",
                display_name="Growth Outlook",
                description="Use this when the question is whether activity is slowing, stabilising or reaccelerating.",
                primary_panels=("growth", "labor"),
                secondary_panels=("cross_asset", "yield_curve"),
                primary_signal_groups=("growth_momentum", "growth_breadth", "labor_demand", "labor_slack"),
                secondary_signal_groups=("credit_risk", "equity_risk", "front_end_rates", "curve_slope"),
                default_questions=(
                    "Is growth momentum slowing materially?",
                    "Is weakness broad-based or concentrated?",
                    "Are labor indicators confirming softer activity?",
                    "Do markets indicate a benign slowdown or a growth scare?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "activity_momentum",
                    "breadth_and_drivers",
                    "labor_confirmation",
                    "cross_asset_confirmation",
                    "rates_implications",
                    "counter_evidence",
                    "risks_and_watch_list",
                ),
                default_watch_questions=(
                    "Is the growth composite still weakening?",
                    "Are payrolls and claims moving together?",
                    "Are credit and volatility confirming the slowdown?",
                ),
                required_evidence_groups=("growth_momentum", "growth_breadth", "labor_demand"),
                optional_evidence_groups=("labor_slack", "credit_risk", "equity_risk", "front_end_rates", "curve_slope"),
                hypotheses=(
                    _hypothesis(
                        "moderate_but_slowing",
                        "Moderate but slowing expansion",
                        "Growth is cooling, but the evidence still points to expansion rather than contraction.",
                        ("growth_momentum", "growth_breadth", "labor_demand"),
                        support_signal_groups=("growth_momentum", "growth_breadth", "labor_demand"),
                        challenge_signal_groups=("credit_risk", "equity_risk"),
                    ),
                    _hypothesis(
                        "broad_deterioration",
                        "Broad growth deterioration",
                        "The activity mix has weakened across more than one channel.",
                        ("growth_momentum", "labor_demand", "credit_risk"),
                        support_signal_groups=("growth_momentum", "growth_breadth", "labor_demand", "credit_risk", "equity_risk"),
                        challenge_signal_groups=("labor_slack",),
                    ),
                    _hypothesis(
                        "reacceleration",
                        "Reacceleration or resilience",
                        "Current evidence still allows for a firmer-than-feared growth path.",
                        ("growth_breadth", "labor_demand"),
                        support_signal_groups=("growth_breadth", "labor_demand"),
                        challenge_signal_groups=("credit_risk", "equity_risk", "labor_slack"),
                    ),
                ),
            ),
        ),
        (
            "labor_policy",
            IssueCategoryConfig(
                category_id="labor_policy",
                display_name="Labor Market and Fed Policy",
                description="Use this when the main issue is whether labor conditions are cooling enough to alter policy pressure.",
                primary_panels=("labor",),
                secondary_panels=("growth", "inflation", "yield_curve", "cross_asset"),
                primary_signal_groups=("labor_demand", "labor_slack", "labor_wage_pressure", "labor_tightness", "labor_supply"),
                secondary_signal_groups=("growth_momentum", "medium_term_inflation_pricing", "front_end_rates", "credit_risk", "market_volatility"),
                default_questions=(
                    "Is the labor market cooling or weakening?",
                    "Is wage growth easing enough to reduce policy pressure?",
                    "Does the labor mix support Fed easing?",
                    "Are claims signalling deterioration ahead of payrolls?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "hiring_momentum",
                    "unemployment_and_claims",
                    "wage_pressure",
                    "vacancies_and_quits",
                    "broader_growth_context",
                    "policy_implications",
                    "market_confirmation",
                    "counter_evidence",
                    "invalidation_conditions",
                    "risks_and_watch_list",
                ),
                default_watch_questions=(
                    "Do claims and payrolls continue to soften together?",
                    "Is wage pressure still easing?",
                    "Are vacancies and quits pointing to rebalancing?",
                ),
                required_evidence_groups=("labor_demand", "labor_slack", "labor_wage_pressure"),
                optional_evidence_groups=("labor_tightness", "labor_supply", "growth_momentum", "medium_term_inflation_pricing", "front_end_rates"),
                hypotheses=(
                    _hypothesis(
                        "benign_rebalancing",
                        "Benign labor-market rebalancing",
                        "Labor conditions are cooling without yet showing a broad deterioration.",
                        ("labor_demand", "labor_slack", "labor_wage_pressure"),
                        support_signal_groups=("labor_demand", "labor_slack", "labor_wage_pressure"),
                        challenge_signal_groups=("credit_risk", "market_volatility"),
                    ),
                    _hypothesis(
                        "emerging_growth_scare",
                        "Emerging growth scare",
                        "Labor weakness is starting to look like an activity slowdown rather than a simple normalisation.",
                        ("labor_demand", "growth_momentum", "credit_risk"),
                        support_signal_groups=("labor_demand", "growth_momentum", "credit_risk", "market_volatility"),
                        challenge_signal_groups=("labor_tightness",),
                    ),
                    _hypothesis(
                        "too_tight",
                        "Labor conditions remain too tight",
                        "The labor market still looks firm enough to keep the Fed cautious.",
                        ("labor_tightness", "labor_wage_pressure"),
                        support_signal_groups=("labor_tightness", "labor_wage_pressure", "labor_demand"),
                        challenge_signal_groups=("labor_slack", "growth_momentum"),
                    ),
                ),
            ),
        ),
        (
            "treasury_curve",
            IssueCategoryConfig(
                category_id="treasury_curve",
                display_name="Treasury Yields and Curve Dynamics",
                description="Use this when the issue is the source of a Treasury move or a curve steepening/flattening.",
                primary_panels=("yield_curve", "nelson_siegel"),
                secondary_panels=("inflation", "growth", "cross_asset", "labor"),
                primary_signal_groups=("treasury_level_move", "front_end_rates", "curve_slope", "long_end_curve", "curve_curvature"),
                secondary_signal_groups=("medium_term_inflation_pricing", "growth_momentum", "labor_wage_pressure", "credit_risk", "market_volatility"),
                default_questions=(
                    "Why did the Treasury curve steepen or flatten?",
                    "Was the move driven by the front end or long end?",
                    "Was the move primarily level-, slope- or curvature-driven?",
                    "Do inflation, growth and cross-asset signals support the rates move?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "observed_treasury_move",
                    "tenor_attribution",
                    "curve_decomposition",
                    "inflation_context",
                    "growth_and_labor_context",
                    "cross_asset_confirmation",
                    "most_consistent_interpretation",
                    "alternative_explanations",
                    "data_gaps",
                    "rates_view_and_watch_list",
                ),
                default_watch_questions=(
                    "Does the front end continue to drive the move?",
                    "Do inflation expectations remain consistent with the move?",
                    "Is Nelson-Siegel slope confirming the direct curve signal?",
                ),
                required_evidence_groups=("treasury_level_move", "curve_slope", "long_end_curve"),
                optional_evidence_groups=("front_end_rates", "curve_curvature", "medium_term_inflation_pricing", "growth_momentum", "labor_wage_pressure", "credit_risk", "market_volatility"),
                hypotheses=(
                    _hypothesis(
                        "policy_path_repricing",
                        "Policy-path repricing",
                        "The Treasury move mostly reflects changing Fed path expectations.",
                        ("front_end_rates", "treasury_level_move", "curve_slope"),
                        support_signal_groups=("front_end_rates", "treasury_level_move", "curve_slope"),
                        challenge_signal_groups=("long_end_curve",),
                    ),
                    _hypothesis(
                        "growth_defensive",
                        "Growth-driven defensive move",
                        "The move is consistent with weaker activity and a defensive bid for duration.",
                        ("growth_momentum", "credit_risk", "market_volatility"),
                        support_signal_groups=("growth_momentum", "credit_risk", "market_volatility", "curve_slope"),
                        challenge_signal_groups=("front_end_rates",),
                    ),
                    _hypothesis(
                        "inflation_repricing",
                        "Inflation or long-end repricing",
                        "The move is driven by inflation compensation or the long end rather than policy alone.",
                        ("medium_term_inflation_pricing", "long_end_curve"),
                        support_signal_groups=("medium_term_inflation_pricing", "long_end_curve", "curve_curvature"),
                        challenge_signal_groups=("front_end_rates",),
                    ),
                    _hypothesis(
                        "mixed_technical",
                        "Mixed technical curve move",
                        "Multiple technical factors are moving together without a single clean macro driver.",
                        ("treasury_level_move", "curve_curvature"),
                        support_signal_groups=("treasury_level_move", "curve_slope", "curve_curvature", "long_end_curve"),
                    ),
                ),
            ),
        ),
        (
            "soft_landing_growth_scare",
            IssueCategoryConfig(
                category_id="soft_landing_growth_scare",
                display_name="Soft Landing versus Growth Scare",
                description="Use this when the key question is whether a slowdown looks benign or recessionary.",
                primary_panels=("growth", "labor", "cross_asset"),
                secondary_panels=("inflation", "yield_curve", "nelson_siegel"),
                primary_signal_groups=("growth_momentum", "growth_breadth", "labor_demand", "labor_slack", "credit_risk", "equity_risk", "market_volatility"),
                secondary_signal_groups=("realized_inflation", "medium_term_inflation_pricing", "front_end_rates", "curve_slope"),
                default_questions=(
                    "Are markets still pricing a soft landing?",
                    "Is the slowdown benign or recessionary?",
                    "Do risk assets confirm lower-rate expectations?",
                    "What evidence would shift the view toward a growth scare?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "base_case",
                    "evidence_for_benign_slowing",
                    "evidence_for_growth_risk",
                    "inflation_constraint",
                    "labor_conditions",
                    "cross_asset_verdict",
                    "rates_implications",
                    "counter_evidence",
                    "invalidation_conditions",
                    "risks_and_watch_list",
                ),
                default_watch_questions=(
                    "Are credit and volatility confirming the slowdown?",
                    "Are lower yields accompanied by weaker risk assets?",
                    "Is inflation still constraining a benign-easing view?",
                ),
                required_evidence_groups=("growth_momentum", "labor_demand", "credit_risk"),
                optional_evidence_groups=("growth_breadth", "labor_slack", "equity_risk", "market_volatility", "realized_inflation", "medium_term_inflation_pricing", "front_end_rates", "curve_slope"),
                hypotheses=(
                    _hypothesis(
                        "soft_landing",
                        "Soft landing / benign easing",
                        "Growth is slowing without the broader mix deteriorating into recessionary stress.",
                        ("growth_momentum", "labor_slack", "credit_risk"),
                        support_signal_groups=("growth_momentum", "labor_slack", "credit_risk", "equity_risk"),
                        challenge_signal_groups=("market_volatility", "curve_slope"),
                    ),
                    _hypothesis(
                        "disinflationary_slowdown",
                        "Disinflationary slowdown",
                        "The slowdown is easing inflation pressure without a sharp risk-off break.",
                        ("realized_inflation", "medium_term_inflation_pricing", "growth_momentum"),
                        support_signal_groups=("realized_inflation", "medium_term_inflation_pricing", "growth_momentum", "labor_slack"),
                        challenge_signal_groups=("credit_risk", "market_volatility"),
                    ),
                    _hypothesis(
                        "growth_scare",
                        "Growth scare",
                        "Weak activity is beginning to show up in markets and labour conditions together.",
                        ("growth_breadth", "labor_demand", "credit_risk", "market_volatility"),
                        support_signal_groups=("growth_breadth", "labor_demand", "credit_risk", "market_volatility", "equity_risk"),
                    ),
                    _hypothesis(
                        "mixed_low_confidence",
                        "Mixed or low-confidence regime",
                        "Evidence is too cross-cutting to choose a single clean regime.",
                        ("growth_momentum", "labor_demand", "credit_risk"),
                        support_signal_groups=("growth_momentum", "growth_breadth", "labor_demand", "labor_slack", "credit_risk", "equity_risk", "market_volatility"),
                    ),
                ),
            ),
        ),
        (
            "cross_asset_risk",
            IssueCategoryConfig(
                category_id="cross_asset_risk",
                display_name="Cross-Asset Risk Sentiment",
                description="Use this when the main issue is whether credit, equities, volatility and the dollar are confirming the macro story.",
                primary_panels=("cross_asset",),
                secondary_panels=("yield_curve", "growth", "inflation", "labor"),
                primary_signal_groups=("credit_risk", "equity_risk", "market_volatility", "dollar_conditions", "cross_asset_regime"),
                secondary_signal_groups=("treasury_level_move", "front_end_rates", "growth_momentum", "medium_term_inflation_pricing"),
                default_questions=(
                    "Are broader markets risk-on or risk-off?",
                    "Are lower yields consistent with benign easing or a growth scare?",
                    "Do credit, equities and volatility agree?",
                    "Is the dollar confirming the broader macro narrative?",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "credit",
                    "equities_and_volatility",
                    "dollar",
                    "rates_context",
                    "macro_confirmation",
                    "conflicting_signals",
                    "risks_and_watch_list",
                ),
                default_watch_questions=(
                    "Is credit widening or tightening?",
                    "Is VIX confirming the direction of risk sentiment?",
                    "Is the dollar aligned with the macro message?",
                ),
                required_evidence_groups=("credit_risk", "equity_risk", "market_volatility"),
                optional_evidence_groups=("dollar_conditions", "cross_asset_regime", "treasury_level_move", "front_end_rates", "growth_momentum", "medium_term_inflation_pricing"),
                hypotheses=(
                    _hypothesis(
                        "broad_risk_on",
                        "Broad risk-on",
                        "Credit, equities and volatility are aligned with a constructive risk backdrop.",
                        ("credit_risk", "equity_risk", "market_volatility"),
                        support_signal_groups=("credit_risk", "equity_risk", "market_volatility"),
                        challenge_signal_groups=("dollar_conditions",),
                    ),
                    _hypothesis(
                        "broad_risk_off",
                        "Broad risk-off",
                        "The market mix is pointing to stress rather than benign easing.",
                        ("credit_risk", "equity_risk", "market_volatility"),
                        support_signal_groups=("credit_risk", "equity_risk", "market_volatility", "dollar_conditions"),
                    ),
                    _hypothesis(
                        "benign_easing",
                        "Benign easing",
                        "Risk assets are improving alongside falling rates without obvious stress signals.",
                        ("treasury_level_move", "credit_risk", "market_volatility"),
                        support_signal_groups=("credit_risk", "equity_risk", "market_volatility", "treasury_level_move"),
                    ),
                    _hypothesis(
                        "growth_scare_cross_asset",
                        "Growth scare",
                        "Cross-asset moves look defensive enough to imply growth concern.",
                        ("credit_risk", "market_volatility", "treasury_level_move"),
                        support_signal_groups=("credit_risk", "market_volatility", "treasury_level_move"),
                        challenge_signal_groups=("equity_risk",),
                    ),
                ),
            ),
        ),
        (
            "custom",
            IssueCategoryConfig(
                category_id="custom",
                display_name="Custom Issue",
                description="Use this when you want to manually define the evidence set and note template for a bespoke question.",
                primary_panels=(),
                secondary_panels=(),
                primary_signal_groups=(),
                secondary_signal_groups=(),
                default_questions=(
                    "Define a custom macro question.",
                ),
                note_section_order=(
                    "research_question",
                    "conclusion",
                    "supporting_evidence",
                    "counter_evidence",
                    "implications",
                    "risks_and_watch_list",
                    "data_gaps",
                ),
                default_watch_questions=(
                    "What evidence would change the view?",
                ),
                required_evidence_groups=(),
                optional_evidence_groups=(),
                hypotheses=(),
            ),
        ),
    ]
)


def get_issue_category(category_id: str) -> IssueCategoryConfig:
    return ISSUE_CATEGORY_REGISTRY.get(category_id, ISSUE_CATEGORY_REGISTRY["custom"])
